server:
  servlet:
    session:
      timeout: 1800
#  port: 8082       

spring:
  datasource:
    username: root
    password: pythoner
    url: jdbc:mysql://127.0.0.1:3306/alicia?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
#    mode: LEGACYHTML5
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
#  profiles:
#    active: dev
#  servlet:
#    multipart:
#      max-file-size: 30Mb
#      max-request-size: 30Mb
    
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:com/**/*Mapper.xml
#  typeAliasesPackage: com.fullexception.entity
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.fullexception.entity
