server:
  servlet:
    session:
      timeout: 1800
      
spring:
  datasource:
    username: root
    password: pythoner
    url: jdbc:mysql://127.0.0.1:3306/alicia?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: HTML5
    
mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.fullexception.entity
  